name: Build Lambda ZIP and Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Go version
        run: go version

      - name: Download modules
        run: go mod download

      - name: Build linux/amd64 bootstrap binary
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: '0'
        run: |
          mkdir -p dist
          go build -trimpath -ldflags "-s -w" -o dist/bootstrap ./main.go

      - name: Package zip
        run: |
          cd dist
          zip -9 lambda.zip bootstrap

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          files: |
            dist/lambda.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
