name: Terraform

on:
  push:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      TF_IN_AUTOMATION: "true"
      # Use AWS_REGION from secrets if provided; defaults to us-west-2 when not set
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials (assume role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::587431634228:role/GitHubThingsNetworkHandler
          role-session-name: terraform-ci
          aws-region: ${{ env.AWS_REGION || 'us-west-2' }}

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.sha }}
          path: terraform/tfplan

      - name: Terraform apply (main branch only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve tfplan
